### ISSUE TITLE
persistent history storage

### ISSUE THREAD

**Issue by msehnout** [MovingtoMars/liner#10]
There is currently no way to store a history and load it from a file.

possible sources of inspiration:
[ion from redox](https://github.com/redox-os/ion/blob/master/src/history.rs)
[readline written in Go](https://github.com/chzyer/readline/blob/master/history.go)

If this is a desired feature in this project, I will work on it.

**Comment by MovingtoMars** [comment]
Hmm, do you think this belongs in liner? I saw it more as something to be done by the code using liner.

Opinion, @skylerberg?

**Comment by skylerberg** [comment]
@MovingtoMars Either Ion or Liner works for me because both use it. Liner needs to use it for the up-arrow and Ion needs to use it for the `history` command. If it goes in Liner then Liner will need to allow external code to get the history so that Ion can use Liner's history in in the `history` command.

**Comment by msehnout** [comment]
Yes, I was thinking about this as well, because Ion already has history module, but then we need some API to fill the history, so it can be used, right?

**Comment by MovingtoMars** [comment]
Well currently you can just convert each `String` to `Buffer` and call `history.push(...)` on the `Context`.

However, it might be worth it to change `Vec<Buffer>` into it's own `History` struct in liner.

**Comment by msehnout** [comment]
But using this approach, history would be stored twice. Once in ion history and the second one in liner. I think we should use ion's history directly or move this functionality into liner.

**Comment by MovingtoMars** [comment]
That was what I meant, moving the functionality into liner, that is.

**Comment by msehnout** [comment]
ok, I'm working on this.
