### ISSUE TITLE
fish-like autosuggestions

### ISSUE THREAD

**Issue by msehnout** [MovingtoMars/liner#31]
Fish has this nice feature of suggesting commands from history without pressing Ctrl+R every time:
https://fishshell.com/docs/current/tutorial.html#tut_autosuggestions

Would you like to have something like this implemented in liner?

**Comment by mmstick** [comment]
I would certainly like to see this for the `Ion` shell.

**Comment by msehnout** [comment]
@MovingtoMars I'm looking at the code, but not sure where to start. Where would you suggest me to implement this and do you want to make it optional?

**Comment by MovingtoMars** [comment]
I'd say create a `HistoryCommandCompleter` that implements the `Completer` trait.

**Comment by msehnout** [comment]
I think that is missing the point of autocompletion, because it would not be automatic, i.e. without pressing tab or Ctrl+R. Have you seen my PR?

**Comment by MovingtoMars** [comment]
Oh sorry, just looked. It's great!

**Comment by mmstick** [comment]
@msehnout Think you could also add the dedup() line from my PR to yours, to avoid needing to merge two PRs?

**Comment by msehnout** [comment]
@mmstick Just the one line? I can see that we have conflicting changes, but I think it won't be hard to merge them by hand.

**Comment by mmstick** [comment]
@msehnout That one line is the only one that matters. The rest are just recommendations from Clippy.

**Comment by msehnout** [comment]
@mmstick ok no problem

**Comment by MovingtoMars** [comment]
Is there anything else that needs to be done for this?

**Comment by msehnout** [comment]
There probably is according to Ion's readme:
https://github.com/redox-os/ion/blob/master/README.md
But I'm not sure what @mmstick meant.

**Comment by mmstick** [comment]
What's missing right now is autocompletions with the right arrow key.

**Comment by MovingtoMars** [comment]
That's done as of #44
