### ISSUE TITLE
Multiline Editing

### ISSUE THREAD

**Issue by mmstick** [MovingtoMars/liner#38]
So I currently have a limited form of multiline comments / commands in the Ion shell which works great for scripts, but for the REPL there is no means of going back and editing previous lines that have been entered, but not yet submitted for completion. Does liner currently support this feature in some way?

**Comment by iamcodemaker** [comment]
Liner supports history editing (see example.rs). Though I tested editing history entries with newlines in them and it does not work as expected.

**Comment by iamcodemaker** [comment]
Note: editing history lines that are very long and wrapped works, but not editing history with `\n` characters in it. That behaves strangely.

**Comment by MovingtoMars** [comment]
Implemented as of 06bb85c86f8e8538758ef8d272657dbe193bfb74
