### ISSUE TITLE
access previous argument

### ISSUE THREAD

**Issue by aeosynth** [MovingtoMars/liner#52]
in bash, `<Esc>.`, and `<Alt>.` insert the last argument of the previous command; multiple presses go further into the history. requesting this feature.

**Comment by MovingtoMars** [comment]
I've implemented this for `alt+.` Unfortunately, Termion doesn't support using esc as a modifier at the moment, so I'll leave this open until then.

**Comment by MovingtoMars** [comment]
Also, arg fetching doesn't work properly for args with quotes or escaped spaces yet.
