### ISSUE TITLE
Initial buffer

### ISSUE THREAD

**Issue by commandline** [MovingtoMars/liner#64]
I have a cli I am writing that saves some data to file based on an initial run. Re-running loads that file, it would be nice to present the saved values for editing. Other than re-implementing some internal functions of Context, I cannot see a way to do this really. If I could pass my own buffer into an additional read_line method, that would very nicely do it. I'll see if I can come up with a quick PR that demonstrates what I mean.

**Comment by MovingtoMars** [comment]
How about adding `EventKind::EditorInit` which is sent when a new editor is created? And when you receive that event, you can insert the text you want.

**Comment by iamcodemaker** [comment]
Is that better than adding a new constructor? Seems less discoverable.

**Comment by commandline** [comment]
The event idea works for me. I initially started down that path but then realized the user experience was pretty crummy that the buffer only get updated if the user hit a kit.

**Comment by MovingtoMars** [comment]
I've added `Context::read_line_with_init_buffer()` and `Editor::new_with_init_buffer()` in 5862d60d8ef477f4b0ee9163906b4f4c501afa53.

I think I need to look into changing how events work slightly before that option is good.

**Comment by commandline** [comment]
Thank you!
