### ISSUE TITLE
kill by path-fragment

### ISSUE THREAD

**Issue by aeosynth** [MovingtoMars/liner#73]
in fish, ctrl+w doesn't kill the entire word (string of non-whitespace), it kills up to the closest slash. requesting this feature.

**Comment by valpackett** [comment]
+1. In zsh, this is configurable: words are defined as sequences of (alphanumeric || in `$WORDCHARS`) characters. By default `$WORDCHARS` is `*?_-.[]~=/&;!#$%^(){}<>`, and removing the `/` from there accomplishes the fish behavior.

**Comment by aeosynth** [comment]
@myfreeweb this repo is inactive, and was forked https://gitlab.redox-os.org/redox-os/liner
