### ISSUE TITLE
"Ctrl+["=Leave insert mode in vi

### ISSUE THREAD

**Issue by liamnaddell** [MovingtoMars/liner#86]
I came from the redox-os project which uses liner in ion, and I tried to run set -o vi and found this.
Im working on this thing, I forked it and I think I fixed it: :crossed_fingers: . You probably should check my work because I have no idea how this project works.

My fork is here: https://github.com/liamnaddell/liner

Should I pr?

I also "added" two more tests that use ctrl+[ instead of Esc

**Comment by iamcodemaker** [comment]
Go ahead and submit a PR. I left a comment on one of your commits. The maintainer for this project seems to be AWOL at the moment, so I'm not sure this will get merged but go ahead and submit it anyway.

**Comment by liamnaddell** [comment]
Pr is at https://github.com/MovingtoMars/liner/pull/88

**Comment by ngirard** [comment]
@liamnaddell You might want to close this issue, in order to make it #94 more visible.

**Comment by liamnaddell** [comment]
Closed
