### ISSUE TITLE
Editor clears ALL text after it, not just the current line

### ISSUE THREAD

**Issue by anirudhb** [MovingtoMars/liner#90]
This is not good for my use case, where I need to have an editor alongside some static text. (E.g. for editing a field)

Could this be changed to `clear::CurrentLine` or `clear::UntilNewline`?

If so, I'll open a PR.

**Comment by iamcodemaker** [comment]
I don't fully understand the context, but that might be appropriate. This project is currently unmaintained, but there is a for in redox that is maintained. Submit any PRs there.

**Comment by ngirard** [comment]
@anirudhb You might want to close this issue, in order to make it #94 more visible.

**Comment by anirudhb** [comment]
Fixed in the fork.
