### ISSUE TITLE
Backslash handling

### ISSUE THREAD

**Issue by AdminXVII** [MovingtoMars/liner#92]
`read_line` never exits when the last char on the line is a backslash. It would be useful to at least be able to overwrite the `handle_newline`, or better even, to be able to specify when to end a line.

**Comment by iamcodemaker** [comment]
This project seems to be abandoned. Raise an issue on https://gitlab.redox-os.org/redox-os/liner

**Comment by AdminXVII** [comment]
Done, thank you.

**Comment by ngirard** [comment]
You might want to close this issue, in order to make it #94 more visible.
